name: Docker Image CI

on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fgsc-customer-satisfaction:$(date +%s)
